name: Build

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build x86
        shell: pwsh
        run: msbuild .\src\build\windows\MS_VS2022\Lerc\Lerc.vcxproj /p:Platform=x64 /p:OutDir="$pwd/runtimes/win-x64/native/"
      - name: Build x64
        shell: pwsh
        run: msbuild .\src\build\windows\MS_VS2022\Lerc\Lerc.vcxproj /p:Platform=x86 /p:OutDir="$pwd/runtimes/win-x86/native/"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: runtimes/

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Create directories
        run: mkdir -p runtimes/linux-x64/native/
      - name: Build x64
        run: |
          mkdir tmp
          cd tmp
          cmake ../src
          make
          cp *.so.* ../runtimes/linux-x64/native/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: runtimes/

  package:
    runs-on: ubuntu-latest
    needs: [linux, windows]
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: runtimes

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: runtimes

      - name: Package
        run: nuget pack

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: *.nupkg
          